- alias: outside_irrigation_new_seed_phase_1_time
  trigger:
    - platform: time
      at: '08:00:00'
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '12:00:00'
    - platform: time
      at: '13:30:00'
    - platform: time
      at: '15:00:00'
    - platform: time
      at: '16:30:00'
    - platform: time
      at: '18:00:00'
  condition:
    - condition: state
      entity_id: input_select.irrigation
      state: New Seed (Phase 1)
    - condition: numeric_state
      entity_id: sensor.netatmo_home_indoor_rain_rain
      below: .1
  action:
    - service: python_script.irrigation_run_all_zones
      data:
        duration: 480
- alias: outside_irrigation_new_seed_phase_2_time
  trigger:
    - platform: sun
      event: sunrise
  condition:
    - condition: state
      entity_id: input_select.irrigation
      state: New Seed (Phase 2)
    - condition: numeric_state
      entity_id: sensor.netatmo_home_indoor_rain_rain
      below: .1
    - condition: numeric_state
      entity_id: sensor.netatmo_home_indoor_rain_rain_today
      below: 1
  action:
    - service: script.post_slack_message
      data:
        message: Started watering for new seed
    - service: python_script.irrigation_run_all_zones
      data:
        duration: 900
- alias: outside_irrigation_maintenance_syringe_time
  trigger:
    platform: time
    at: '14:30:00'
  condition:
    - condition: state
      entity_id: input_select.irrigation
      state: Maintenance
    - condition: state
      entity_id: binary_sensor.excessive_heat_today
      state: 'on'
  action:
    - service: python_script.irrigation_run_all_zones
      data:
        duration: 360
