- platform: template
  sensors:
    low_visibility:
      value_template: >
        {{
          is_state('binary_sensor.nighttime', 'on') or
          (
            states('sensor.openweathermap_cloud_coverage') | float > 75 and
            states('sensor.openweathermap_rain') | float > 0
          )
        }}
      delay_off:
        minutes: 15
    near_freezing_last_two_days:
      value_template: >
        {% if is_state('sensor.temperature_last_two_days', 'unavailable') %}
          unavailable
        {% else %}
          {{ states('sensor.temperature_last_two_days') | float < 40 }}
        {% endif %}
      delay_on:
        hours: 2
    high_winds_last_hour:
      value_template: >
        {% if is_state('sensor.netatmo_home_indoor_wind_wind_strength', 'unavailable') %}
          unavailable
        {% else %}
          {{ states('sensor.netatmo_home_indoor_wind_wind_strength') | float > 5 }}
        {% endif %}
      delay_off:
        minutes: 15
    poor_fountain_conditions:
      value_template: >
        {{
          is_state('binary_sensor.near_freezing_last_two_days', 'on') or
          is_state('binary_sensor.high_winds_last_hour', 'on')
        }}
    home:
      value_template: "{{ states('device_tracker.phone_1') == 'home' or states('device_tracker.phone_2') == 'home' }}"
