- platform: template
  sensors:
    raining:
      availability_template: "{{ states('sensor.netatmo_home_rain_rain') | is_number }}"
      value_template: "{{ states('sensor.netatmo_home_rain_rain') | float > 0 }}"
    low_visibility:
      value_template: >
        {{
          is_state('binary_sensor.nighttime', 'on') or 
          is_state('binary_sensor.raining', 'on') 
        }}
    near_freezing_last_two_days:
      availability_template: "{{ states('sensor.temperature_last_two_days') | is_number }}"
      value_template: "{{ states('sensor.temperature_last_two_days') | float < 40 }}"
    high_winds_last_hour:
      availability_template: "{{ states('sensor.netatmo_home_wind_gust_strength') | is_number }}"
      value_template: "{{ states('sensor.netatmo_home_wind_gust_strength') | float > 5 }}"
    poor_fountain_conditions:
      value_template: >
        {{
          is_state('binary_sensor.near_freezing_last_two_days', 'on') or
          is_state('binary_sensor.high_winds_last_hour', 'on')
        }}
      delay_off:
        minutes: 15
    home:
      value_template: "{{ states('device_tracker.phone_1') == 'home' or states('device_tracker.phone_2') == 'home' }}"
