- platform: template
  sensors:
    near_freezing_last_two_days:
      value_template: "{{ states('sensor.temperature_last_two_days') | float < 35 }}"
    high_winds_last_hour:
      value_template: "{{ states('sensor.netatmo_weather_indoor_wind_wind_strength') | float > 5 }}"
    poor_fountain_conditions:
      delay_on:
        minutes: 15
      value_template: >
        {{
          is_state('binary_sensor.near_freezing_last_two_days', 'on') or
          is_state('binary_sensor.high_winds_last_hour', 'on')
        }}
    excessive_heat_today_already:
      value_template: "{{ states('sensor.netatmo_weather_indoor_outdoor_max_temp') | float > 85 }}"
    excessive_heat_today_predicted:
      value_template: >
        {% set start = (now().replace(hour=0,minute=0,second=0).timestamp() * 1000) | int %}
        {% set end = start + 86400000 %}
        {{
           state_attr('weather.openweathermap', 'forecast') |
           selectattr('datetime', '>', start) |
           selectattr('datetime','<=', end) |
           map(attribute='temperature') |
           list |
           max
        }}
    excessive_heat_today:
      value_template: "{{ states('sensor.excessive_heat_today_already') or states('sensor.excessive_heat_today_predicted') }}"
    is_holiday_season:
      value_template: >
        {% set month = now().month %}
        {% set day = now().day %}
        {{ (month == 11 and day > 26) or (month == 12 and day < 31) }}
