cloud:
homeassistant: !include homeassistant.yaml
mobile_app:

# Components
automation: !include_dir_merge_list automation
config:
history:
input_boolean: !include input_boolean.yaml
logbook:
recorder: !include recorder.yaml
script: !include_dir_list script
system_health:
timer: !include timer.yaml

# Platforms
binary_sensor: !include_dir_merge_list binary_sensor
climate: !include_dir_merge_list climate
light: !include_dir_merge_list light
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
vacuum: !include_dir_merge_list vacuum
