cloud:
homeassistant: !include homeassistant.yaml
lovelace: !include lovelace.yaml

# Components
automation: !include automation.yaml
config:
discovery:
frontend: !include frontend.yaml
history:
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
logbook: !include logbook.yaml
nest: !include nest.yaml
python_script:
recorder: !include recorder.yaml
rest_command: !include rest_command.yaml
roomba: !include roomba.yaml
script: !include script.yaml
sun:
system_health:
timer: !include timer.yaml
zwave: !include zwave.yaml

# Platforms
binary_sensor: !include_dir_merge_list binary_sensor
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
vacuum: !include_dir_merge_list vacuum
