path: default_view
title: Overview
badges: []
panel: true
cards:
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - device_tracker.tom_phone
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.inside_lights
            name: Inside
            icon_height: 50px
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.inside_lights
          - type: entity-button
            entity: switch.upstairs_lights
            name: Upstairs
            icon_height: 50px
          - type: entity-button
            entity: switch.downstairs_lights
            name: Downstairs
            icon_height: 50px
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.downstairs_lights
          - type: entity-button
            entity: switch.outside_lights
            name: Outside
            icon_height: 50px
            tap_action:
              action: call-service
              service: switch.toggle
              service_data:
                entity_id: switch.outside_lights
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: input_boolean.sleep_mode
            icon: 'mdi:sleep'
            icon_height: 50px
            show_name: false
            tap_action:
              action: call-service
              service: input_boolean.turn_on
              service_data:
                entity_id: input_boolean.sleep_mode
          - type: entity-button
            entity: input_boolean.sleep_mode
            icon: 'mdi:sleep-off'
            icon_height: 50px
            show_name: false
            tap_action:
              action: call-service
              service: input_boolean.turn_off
              service_data:
                entity_id: input_boolean.sleep_mode
          - type: entity-button
            entity: vacuum.roomba
            icon_height: 50px
            show_name: false
      - type: horizontal-stack
        cards:
          - type: picture-glance
            camera_image: camera.porch
            entities:
              - light.front_yard
              - lock.front_door
              - binary_sensor.front_door_open
            aspect_ratio: '16:9'
          - type: picture-glance
            camera_image: camera.office
            entities:
              - light.office
      - type: horizontal-stack
        cards:
          - type: picture-glance
            camera_image: camera.garage
            entities:
              - lock.garage_door
              - cover.garage_lift_door
              - binary_sensor.garage_door_open
          - type: picture-glance
            camera_image: camera.sunroom
            entities:
              - light.sunroom
              - lock.sunroom_door
              - binary_sensor.sunroom_door_open
      - type: horizontal-stack
        cards:
          - type: picture-glance
            entities:
              - light.backyard
              - lock.deck_door
              - binary_sensor.deck_door_open
            camera_image: camera.deck
          - type: picture-glance
            camera_image: camera.backyard
            entities:
              - light.backyard
      - type: alarm-panel
        entity: alarm_control_panel.abode_alarm
      - type: thermostat
        entity: climate.hallway
icon: 'mdi:home'
