path: default_view
title: Overview
badges: []
panel: true
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: entity
            entity: device_tracker.phone_1
          - type: entity
            entity: device_tracker.phone_2
          - type: entity-button
            entity: input_boolean.sleep_mode_enabled
            icon_height: 50px
            icon: 'mdi:sleep'
            show_name: false
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.inside
            name: Inside
            icon_height: 50px
          - type: entity-button
            entity: light.upstairs
            name: Upstairs
            icon_height: 50px
          - type: entity-button
            entity: light.downstairs
            name: Downstairs
            icon_height: 50px
          - type: entity-button
            entity: light.outside
            name: Outside
            icon_height: 50px
      - type: alarm-panel
        entity: alarm_control_panel.abode_alarm
icon: 'mdi:home'
