path: security_view
title: Security
badges: []
cards:
  - type: 'custom:auto-entities'
    card:
      type: entities
      title: Security
      show_header_toggle: false
    filter:
      include:
        - entity_id: "lock.*"
        - entity_id: "cover.*"
        - entity_id: "binary_sensor.*door_open"
        - entity_id: "binary_sensor.*glass*"
        - entity_id: "binary_sensor.*siren"
  - type: alarm-panel
    entity: alarm_control_panel.abode_alarm
icon: 'mdi:security'
