path: settings_view
title: Settings
badges: []
cards:
  - type: custom:fold-entity-row
    head:
      type: section
      label: Automations
    entities:
      - type: 'custom:auto-entities'
        card:
          type: entities
        filter:
          include:
            - entity_id: "automation.*"
        sort:
          method: entity_id
  - type: custom:fold-entity-row
    head:
      type: section
      label: Scripts
    entities:
      - type: 'custom:auto-entities'
        card:
          type: entities
        filter:
          include:
            - entity_id: "script.*"
        sort:
          method: entity_id
  - type: custom:fold-entity-row
    head:
      type: section
      label: Inputs
    entities:
      - type: 'custom:auto-entities'
        card:
          type: entities
        filter:
          include:
            - entity_id: "input*.*"
        sort:
          method: entity_id
icon: 'mdi:cellphone-settings-variant'
