- platform: group
  name: "Bathroom Downstairs"
  entities:
    - light.bathroom_downstairs_vanity_lights
- platform: group
  name: "Bathroom Upstairs"
  entities:
    - light.hue_bathroom_upstairs
- platform: group
  name: "Guest Room"
  entities:
    - light.guest_room_main_lights
- platform: group
  name: "Den"
  entities:
    - light.hue_den
- platform: group
  name: "Dining Room"
  entities:
    - light.dining_room_main_lights
- platform: group
  name: "Entryway"
  entities:
    - light.entryway_chandelier
- platform: group
  name: "Family Room"
  entities:
    - light.hue_family_room
- platform: group
  name: "Hallway"
  entities:
    - light.hallway_main_lights
- platform: group
  name: "Kitchen"
  entities:
    - light.hue_kitchen
- platform: group
  name: "Laundry Room"
  entities:
    - light.hue_laundry_room
- platform: group
  name: "Living Room"
  entities:
    - light.hue_living_room
    - light.living_room_main_lights_1
    - light.living_room_main_lights_2
    - light.living_room_main_lights_3
    - light.living_room_main_lights_4
- platform: group
  name: "Main Bedroom"
  entities:
    - light.hue_main_bedroom
- platform: group
  name: "Office"
  entities:
    - light.hue_office
- platform: group
  name: "Sunroom"
  entities:
    - light.sunroom_main_lights

# Groups of groups
- platform: group
  name: "Downstairs"
  entities:
    - light.bathroom_downstairs
    - light.guest_room
    - light.den
    - light.living_room
    - light.sunroom
- platform: group
  name: "Upstairs"
  entities:
    - light.bathroom_upstairs
    - light.dining_room
    - light.entryway
    - light.family_room
    - light.hallway
    - light.kitchen
    - light.laundry_room
    - light.main_bedroom
    - light.office
- platform: group
  name: "Inside"
  entities:
    - light.downstairs
    - light.upstairs
- platform: group
  name: "Backyard"
  entities:
    - light.hue_backyard
- platform: group
  name: "Front Yard"
  entities:
    - light.hue_front_yard
- platform: group
  name: "Outside"
  entities:
    - light.front_yard
    - light.backyard
