- platform: switch
  name: Front Yard Holiday Lights
  entity_id: switch.front_yard_string_light_switch

- platform: switch
  name: Family Room Window Lights
  entity_id: switch.family_room_window_lights

- platform: switch
  name: Family Room Tree Lights
  entity_id: switch.family_room_tree_lights
