- platform: template
  switches:
    fireplace:
      friendly_name: Fireplace
      value_template: "{{ is_state('light.fireplace', 'on') }}"
      turn_on:
        repeat:
          count: 5
          sequence:
            service: light.turn_on
            entity_id: light.fireplace
      turn_off:
        repeat:
          count: 5
          sequence:
            service: light.turn_off
            entity_id: light.fireplace
      icon_template: >
        {% if is_state('light.fireplace', 'on') %}
          mdi:fireplace
        {% else %}
          mdi:fireplace-off
        {% endif %}

- platform: template
  switches:
    family_room_heaters:
      value_template: "{{ is_state('switch.family_room_heater_1', 'on') or is_state('switch.family_room_heater_2', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id:
            - switch.family_room_heater_1
            - switch.family_room_heater_2
      turn_off:
        - service: switch.turn_off
          entity_id:
            - switch.family_room_heater_1
            - switch.family_room_heater_2

- platform: template
  switches:
    office_heaters:
      value_template: "{{ is_state('switch.office_heater_1', 'on') or is_state('switch.office_heater_2', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id:
            - switch.office_heater_1
            - switch.office_heater_2
      turn_off:
        - service: switch.turn_off
          entity_id:
            - switch.office_heater_1
            - switch.office_heater_2
