- platform: template
  switches:
    fireplace:
      friendly_name: Fireplace
      value_template: "{{ is_state('light.fireplace', 'on') }}"
      turn_on:
        service: script.fireplace_on
      turn_off:
        service: script.fireplace_off
      icon_template: >
        {% if is_state('light.fireplace', 'on') %}
          mdi:fireplace
        {% else %}
          mdi:fireplace-off
        {% endif %}
