- platform: template
  switches:
    inside_lights:
      value_template: "{{ is_state('light.inside', 'on') or is_state('switch.dining_room_lights', 'on') }}"
      turn_on:
        service: script.inside_lights_on
      turn_off:
        service: script.inside_lights_off
      icon_template: >
        {%
          if
          is_state('light.inside', 'on') or
          is_state('switch.dining_room_lights', 'on') or
          is_state('switch.holiday_lights', 'on') or
          is_state('switch.desk', 'on')
        %}
          mdi:lightbulb-on
        {% else %}
          mdi:lightbulb-on-outline
        {% endif %}
    downstairs_lights:
      value_template: "{{ is_state('light.downstairs', 'on') }}"
      turn_on:
        service: script.downstairs_lights_on
      turn_off:
        service: script.downstairs_lights_off
      icon_template: >
        {% if is_state('light.downstairs', 'on') %}
          mdi:lightbulb-on
        {% else %}
          mdi:lightbulb-on-outline
        {% endif %}
    upstairs_lights:
      value_template: "{{ is_state('light.upstairs', 'on') or is_state('switch.dining_room_lights', 'on') }}"
      turn_on:
        service: script.upstairs_lights_on
      turn_off:
        service: script.upstairs_lights_off
      icon_template: >
        {% if is_state('light.upstairs', 'on') or is_state('switch.dining_room_lights', 'on') %}
          mdi:lightbulb-on
        {% else %}
          mdi:lightbulb-on-outline
        {% endif %}
    outside_lights:
      value_template: "{{ is_state('light.outside', 'on') or is_state('switch.outdoor_string_holiday_lights', 'on') }}"
      turn_on:
        service: script.outside_lights_on
      turn_off:
        service: script.outside_lights_off
      icon_template: >
        {% if is_state('light.outside', 'on') or is_state('switch.outdoor_string_holiday_lights', 'on') %}
          mdi:lightbulb-on
        {% else %}
          mdi:lightbulb-on-outline
        {% endif %}
    fireplace:
      friendly_name: Fireplace
      value_template: "{{ is_state('light.fireplace', 'on') }}"
      turn_on:
        service: script.fireplace_on
      turn_off:
        service: script.fireplace_off
      icon_template: >
        {% if is_state('light.fireplace', 'on') %}
          mdi:fireplace
        {% else %}
          mdi:fireplace-off
        {% endif %}
