- alias: inside_sleep_mode_changed_off_to_partial
  trigger:
    platform: state
    entity_id: sensor.sleep_mode
    from: 'off'
    to: partial
  mode: restart
  action:
    - service: script.play_sleep_sounds
    - service: switch.turn_off
      data:
        entity_id: switch.dining_room_lights
    - service: light.turn_off
      data:
        entity_id:
          - light.master_bedroom
          - light.hallway_upstairs
          - light.guest_room
          - light.bathroom_upstairs
        transition: "{{ states('input_number.default_light_transition_time') | float }}"
    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen
          - light.family_room
          - light.entryway
        brightness_pct: 15
        transition: "{{ states('input_number.default_light_transition_time') | float }}"
- alias: inside_sleep_mode_changed_partial_to_on
  trigger:
    platform: state
    entity_id: sensor.sleep_mode
    from: partial
    to: 'on'
  mode: restart
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: homeassistant.turn_off
      data:
        entity_id:
          - media_player.dining_room_home
          - media_player.family_room_home
          - media_player.kitchen_chromecast
          - media_player.living_room_home
          - media_player.garage_home
          - media_player.sunroom_home
          - media_player.living_room_desk_home
          - media_player.sony_bravia_tv
          - remote.family_room
    - service: script.inside_lights_off
- alias: inside_sleep_mode_changed_on_to_partial
  trigger:
    platform: state
    entity_id: sensor.sleep_mode
    from: 'on'
    to: partial
  mode: restart
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen
          - light.family_room
          - light.entryway
        brightness_pct: 15
        transition: "{{ states('input_number.default_light_transition_time') | float }}"
    - service: light.turn_on
      data:
        entity_id:
          - light.downstairs
        brightness_pct: 100
        transition: "{{ states('input_number.default_light_transition_time') | float }}"
- alias: inside_sleep_mode_changed_partial_to_off
  trigger:
    platform: state
    entity_id: sensor.sleep_mode
    from: partial
    to: 'off'
  mode: restart
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.master_bedroom_home
    - service: script.reset_google_home_volumes
    - service: script.inside_lights_on
