- alias: backyard_irrigation_maintenance_time
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - thu
    - condition: state
      entity_id: input_select.irrigation
      state: Maintenance
  action:
    - service: python_script.irrigation_run_maintenance
      data:
        zones:
          - 3
          - 4
          - 5
