blueprint:
  name: Check Water Leak
  domain: automation
  input:
    binary_sensor:
    area:

variables:
  area: !input area
  binary_sensor: !input binary_sensor
trigger:
  - platform: time_pattern
    minutes: '/5'
  - entity_id: !input binary_sensor
    platform: state
    to: 'on'
condition:
  condition: state
  entity_id: !input binary_sensor
  state: 'on'
action:
  - parallel:
    - service: notify.notify
      data:
        message: "Water detected: {{ area }}"
        data:
          push:
            badge: 1
    - service: persistent_notification.create
      data:
        title: Water detected
        message: "Water detected: {{ area }}"
        notification_id: check_water_leak_{{ binary_sensor }}
