blueprint:
  name: lights_off_timer_finished
  domain: automation
  input:
    light_entity:
    timer_entity:
    transition:
      default: 3

trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input timer_entity

condition:
  condition: state
  entity_id: !input light_entity
  state: 'on'

action:
  service: script.light_turn_off
  data:
    entity_id: !input light_entity
    transition: !input transition
