blueprint:
  name: lights_off_sleep_mode_on
  domain: automation
  input:
    light_entity:
    transition:
      default: 3

trigger:
  entity_id: input_boolean.sleep_mode_enabled
  platform: state
  from: 'off'
  to: 'on'

condition:
  condition: state
  entity_id: !input light_entity
  state: 'on'

action:
  service: script.light_turn_off
  data:
    entity_id: !input light_entity
    transition: !input transition
