- alias: time_pattern_roomba_night_cleaning_lights_check
  trigger:
    platform: time_pattern
    minutes: '/5'
  condition:
    - condition: state
      entity_id: sensor.sleep_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.roomba_schedule_night_cleaning
      state: 'on'
    - condition: state
      entity_id: light.hue_downstairs
      state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.hue_downstairs
      brightness_pct: 50
      transition: "{{ states('input_number.light_transition') | float }}"
