- alias: time_pattern_sleep_sounds_check
  trigger:
    platform: time_pattern
    minutes: "/55"
  condition:
    condition: state
    entity_id: input_boolean.sleep_mode_enabled
    state: 'on'
  action:
    service: script.play_sleep_sounds
