- alias: time_pattern_water_leak_check
  trigger:
    - platform: time_pattern
      seconds: '/15'
    - entity_id: binary_sensor.downstairs_bathroom_water_detected
      platform: state
      to: 'on'
    - entity_id: binary_sensor.upstairs_bathroom_water_detected
      platform: state
      to: 'on'
    - entity_id: binary_sensor.main_valve_water_detected
      platform: state
      to: 'on'
    - entity_id: binary_sensor.garage_sink_water_detected
      platform: state
      to: 'on'
    - entity_id: binary_sensor.laundry_room_water_detected
      platform: state
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'binary_sensor.downstairs_bathroom_water_detected'
        state: 'on'
      - condition: state
        entity_id: 'binary_sensor.upstairs_bathroom_water_detected'
        state: 'on'
      - condition: state
        entity_id: 'binary_sensor.main_valve_water_detected'
        state: 'on'
      - condition: state
        entity_id: 'binary_sensor.garage_sink_water_detected'
        state: 'on'
      - condition: state
        entity_id: 'binary_sensor.laundry_room_water_detected'
        state: 'on'
  action:
    service: script.post_slack_message
    data_template:
      message: >
        {% if states('binary_sensor.downstairs_bathroom_water_detected') == 'on' %}
          Water detected in downstairs bathroom!
        {% elif states('binary_sensor.upstairs_bathroom_water_detected') == 'on' %}
          Water detected in upstairs bathroom!
        {% elif states('binary_sensor.main_valve_water_detected') == 'on' %}
          Water detected at main valve!
        {% elif states('binary_sensor.garage_sink_water_detected') == 'on' %}
          Water detected at garage sink!
        {% elif states('binary_sensor.laundry_room_water_detected') == 'on' %}
          Water detected in laundry room!
        {% else %}
          Water detected!
        {% endif %}
