- platform: generic_thermostat
  name: Living Room Heat
  heater: switch.fireplace
  target_sensor: sensor.netatmo_home_indoor_temperature
  min_temp: 60
  max_temp: 80
  ac_mode: false
  comfort_temp: 63
  activity_temp: 68
  cold_tolerance: 0.5
  hot_tolerance: 0
  keep_alive:
    minutes: 90
  initial_hvac_mode: "off"
  precision: 0.1

- platform: generic_thermostat
  name: Family Room Heat
  heater: switch.family_room_heat
  target_sensor: sensor.family_room_temperature
  min_temp: 60
  max_temp: 80
  ac_mode: false
  comfort_temp: 63
  activity_temp: 68
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: "off"
  precision: 0.1

- platform: generic_thermostat
  name: Family Room AC
  heater: switch.family_room_ac
  target_sensor: sensor.family_room_temperature
  min_temp: 60
  max_temp: 80
  ac_mode: true
  comfort_temp: 75
  activity_temp: 73
  cold_tolerance: 0
  hot_tolerance: 0.5
  initial_hvac_mode: "off"
  precision: 0.1

- platform: generic_thermostat
  name: Office Heat
  heater: switch.office_heater
  target_sensor: sensor.office_sensor_air_temperature
  min_temp: 60
  max_temp: 80
  ac_mode: false
  comfort_temp: 63
  activity_temp: 68
  cold_tolerance: 0.5
  hot_tolerance: 0
  initial_hvac_mode: "off"
  precision: 0.1
