- platform: openweathermap
  api_key: !secret open_weather_api_key
  forecast: true
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow
    - weather_code
