- platform: template
  sensors:
    default_indoor_brightness:
      unit_of_measurement: '%'
      value_template: >
        {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
          1
        {% elif is_state('binary_sensor.nighttime', 'on') %}
          50
        {% else %}
          100
        {% endif %}
