- platform: template
  sensors:
    time_of_day_brightness:
      unit_of_measurement: '%'
      value_template: >
        {% if is_state('binary_sensor.nighttime', 'on') %}
          30
        {% elif is_state('binary_sensor.late_afternoon', 'on') %}
          75
        {% else %}
          100
        {% endif %}
    sleep_mode_brightness:
      unit_of_measurement: '%'
      value_template: >
        {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
          1
        {% else %}
          {{ states('sensor.time_of_day_brightness') | int }}
        {% endif %}

- platform: template
  sensors:
    dynamic_light_timer_duration:
      value_template: >
        {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
          00:05:00
        {% else %}
          00:15:00
        {% endif %}
