- platform: template
  sensors:
    time_of_day_brightness:
      unit_of_measurement: '%'
      value_template: >
        {% set next_sunset_ts     = as_timestamp(state_attr('sun.sun','next_setting')) %}
        {% set now_ts             = as_timestamp(now()) %}
        {% set minimum_brightness = 20 %}
        {% set maximum_brightness = 100 %}
        {% set ramp_duration_secs = 4 * 3600 %}
        {% set ramp_start_ts      = next_sunset_ts - ramp_duration_secs %}
        {% set solar_elevation    = state_attr('sun.sun','elevation') | float %}
        {% set interval_secs      = 30 * 60 %}
        {% set intervals         = ramp_duration_secs / interval_secs %}
        {% set step_size         = (maximum_brightness - minimum_brightness) / intervals %}
        {% if solar_elevation <= 0 %}
          {{ minimum_brightness }}
        {% elif now_ts < ramp_start_ts %}
          {{ maximum_brightness }}
        {% elif now_ts <= next_sunset_ts %}
          {% set steps_passed    = ((now_ts - ramp_start_ts) // interval_secs) | int %}
          {% set ramp_brightness = maximum_brightness - steps_passed * step_size %}
          {{ [ramp_brightness, minimum_brightness] | max | round(0) }}
        {% else %}
          {{ minimum_brightness }}
        {% endif %}

    sleep_mode_brightness:
      unit_of_measurement: '%'
      value_template: >
        {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
          1
        {% else %}
          {{ states('sensor.time_of_day_brightness') | int }}
        {% endif %}

- platform: template
  sensors:
    dynamic_light_timer_duration:
      value_template: >
        {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
          00:05:00
        {% else %}
          00:15:00
        {% endif %}
