- alias: bathroom_downstairs_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.bathroom_downstairs

- alias: bathroom_downstairs_lights_home_off
  use_blueprint:
    path: lights_off_home_off.yaml
    input:
      light_entity: light.bathroom_downstairs

- alias: bathroom_downstairs_lights_time_of_day_change
  use_blueprint:
    path: lights_dim_time_of_day_brightness_change.yaml
    input:
      light_entity: light.bathroom_downstairs

- alias: bathroom_downstairs_lights_off_timer_finished
  use_blueprint:
    path: lights_off_timer_finished.yaml
    input:
      light_entity: light.bathroom_downstairs
      timer_entity: timer.bathroom_downstairs_lights

- alias: bathroom_downstairs_lights_on
  trigger:
    platform: state
    entity_id: light.bathroom_downstairs
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.bathroom_downstairs_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"

- alias: bathroom_downstairs_lights_on_motion
  use_blueprint:
    path: lights_on_motion.yaml
    input:
      light_entity: light.bathroom_downstairs
      timer: timer.bathroom_downstairs_lights
      motion: binary_sensor.bathroom_downstairs_motion

- alias: bathroom_downstairs_toilet_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.bathroom_downstairs_toilet_water_sensor_water_leak_detected
      area: Downstairs Bathroom Toilet
