- alias: bathroom_upstairs_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.bathroom_upstairs

- alias: bathroom_upstairs_lights_home_on
  use_blueprint:
    path: lights_on_home_on.yaml
    input:
      light_entity: light.bathroom_upstairs

- alias: bathroom_upstairs_lights_home_off
  use_blueprint:
    path: lights_off_home_off.yaml
    input:
      light_entity: light.bathroom_upstairs

- alias: bathroom_upstairs_timer_lights_finished
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bathroom_upstairs_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_upstairs

- alias: bathroom_upstairs_lights_on
  trigger:
    platform: state
    entity_id: light.bathroom_upstairs
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.bathroom_upstairs_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"

- alias: bathroom_upstairs_motion_detected
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_upstairs_motion
    to: 'on'
  action:
    - service: timer.start
      data:
        entity_id: timer.bathroom_upstairs_lights
        duration: "{{ states('sensor.dynamic_light_timer_duration') }}"
    - condition: state
      entity_id: light.bathroom_upstairs
      state: 'off'
    - service: light.turn_on
      data:
        entity_id: light.bathroom_upstairs
        brightness_pct: "{{ states('sensor.sleep_mode_brightness') | float }}"

- alias: bathroom_upstairs_toilet_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.bathroom_upstairs_toilet_water_sensor_water_leak_detected
      area: Upstairs Bathroom Toilet

- alias: bathroom_upstairs_sink_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.bathroom_upstairs_sink_water_sensor_water_leak_detected
      area: Upstairs Bathroom Sink
