- alias: crawl_space_main_line_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.crawl_space_main_line_water_sensor_water_leak_detected
      area: Crawl Space Main Line
