- alias: dining_room_google_home_sleep_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'off'
    to: 'on'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.dining_room_home

- alias: dining_room_google_home_sleep_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'on'
    to: 'off'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.dining_room_home
        volume_level: 0.50
