- alias: entryway_lights_sleep_mode_off
  use_blueprint:
    path: lights_on_sleep_mode_off.yaml
    input:
      light_entity: light.entryway

- alias: entryway_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.entryway

- alias: entryway_front_door_left_open
  trigger:
    entity_id: binary_sensor.front_door_open
    platform: state
    to: 'on'
    for:
      minutes: 15
  action:
    service: notify.notify
    data_template:
      message: Front door is still open!
      data:
        push:
          badge: 1

- alias: entryway_front_door_relock
  trigger:
    entity_id: binary_sensor.front_door_open
    platform: state
    to: 'off'
    for:
      minutes: 15
  action:
    service: lock.lock
    data:
      entity_id: lock.front_door_lock

- alias: entryway_front_door_notify_unlocked
  trigger:
    entity_id: lock.front_door_lock
    platform: state
    to: 'unlocked'
    for:
      minutes: 30
  action:
    service: notify.notify
    data:
      message: Front door is still unlocked!
      data:
        push:
          badge: 1
