- alias: family_room_climate_motion_detected
  trigger:
    entity_id: binary_sensor.family_room_motion
    platform: state
    to: 'on'
  action:
    service: climate.set_preset_mode
    data:
      entity_id:
        - climate.family_room_heat
        - climate.family_room_ac
      preset_mode: activity

- alias: family_room_climate_motion_idle
  trigger:
    entity_id: binary_sensor.family_room_motion
    platform: state
    to: 'off'
    for:
      minutes: 15
  action:
    service: climate.set_preset_mode
    data:
      entity_id:
        - climate.family_room_heat
        - climate.family_room_ac
      preset_mode: comfort

- alias: family_room_climate_arrive_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: climate.turn_on
    data:
      entity_id:
        - climate.family_room_heat
        - climate.family_room_ac

- alias: family_room_climate_depart_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: climate.turn_off
    data:
      entity_id:
        - climate.family_room_heat
        - climate.family_room_ac
