- alias: guest_room_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.guest_room

- alias: guest_room_lights_home_off
  use_blueprint:
    path: lights_off_home_off.yaml
    input:
      light_entity: light.guest_room
