- alias: hallway_lights_sleep_mode_off
  use_blueprint:
    path: lights_on_sleep_mode_off.yaml
    input:
      light_entity: light.hallway
      transition: 300

- alias: hallway_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.hallway
