- alias: inside_lights_sleep_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'on'
    to: 'off'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.inside
        - light.inside_accent
      brightness_pct: "{{ states('sensor.time_of_day_brightness') | float }}"
      transition: 300

- alias: inside_lights_sleep_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'off'
    to: 'on'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.inside
        - light.inside_accent

- alias: inside_lights_home_on
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id:
        - light.inside
        - light.inside_accent
      brightness_pct: "{{ states('sensor.sleep_mode_brightness') | float }}"

- alias: inside_lights_home_off
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.inside
        - light.inside_accent

- alias: inside_arrive_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.abode_alarm

- alias: inside_depart_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.abode_alarm

- alias: inside_sleep_mode_on
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: alarm_control_panel.alarm_arm_home
    data:
      entity_id: alarm_control_panel.abode_alarm

- alias: inside_sleep_mode_off
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.abode_alarm
