- alias: inside_arrive_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.abode_alarm

- alias: inside_depart_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.abode_alarm

- alias: inside_sleep_mode_on
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: alarm_control_panel.alarm_arm_home
    data:
      entity_id: alarm_control_panel.abode_alarm

- alias: inside_sleep_mode_off
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.abode_alarm