- alias: kitchen_lights_sleep_mode_off
  use_blueprint:
    path: lights_on_sleep_mode_off.yaml
    input:
      light_entity: light.kitchen

- alias: kitchen_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.kitchen

- alias: kitchen_lights_home_on
  use_blueprint:
    path: lights_on_home_on.yaml
    input:
      light_entity: light.kitchen

- alias: kitchen_lights_home_off
  use_blueprint:
    path: lights_off_home_off.yaml
    input:
      light_entity: light.kitchen

- alias: kitchen_lights_time_of_day_change
  use_blueprint:
    path: lights_dim_time_of_day_brightness_change.yaml
    input:
      light_entity: light.kitchen

- alias: kitchen_sink_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.kitchen_sink_water_sensor_water_leak_detected
      area: Kitchen Sink

- alias: kitchen_dishwasher_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.kitchen_dishwasher_water_sensor_water_leak_detected
      area: Kitchen Dishwasher

- alias: kitchen_refrigerator_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.kitchen_refrigerator_water_sensor_water_leak_detected
      area: Kitchen Refrigerator
