- alias: laundry_room_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.laundry_room

- alias: laundry_room_lights_home_off
  use_blueprint:
    path: lights_off_home_off.yaml
    input:
      light_entity: light.laundry_room

- alias: laundry_room_lights_time_of_day_change
  use_blueprint:
    path: lights_dim_time_of_day_brightness_change.yaml
    input:
      light_entity: light.laundry_room

- alias: laundry_room_lights_off_timer_finished
  use_blueprint:
    path: lights_off_timer_finished.yaml
    input:
      light_entity: light.laundry_room
      timer_entity: timer.laundry_room_lights

- alias: laundry_room_lights_on
  trigger:
    platform: state
    entity_id: light.laundry_room
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.laundry_room_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"

- alias: laundry_room_motion_detected
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_room_motion
    to: 'on'
  action:
    - service: timer.start
      data:
        entity_id: timer.laundry_room_lights
        duration: "{{ states('sensor.dynamic_light_timer_duration') }}"
    - condition: state
      entity_id: light.laundry_room
      state: 'off'
    - service: light.turn_on
      data:
        entity_id: light.laundry_room
        brightness_pct: "{{ states('sensor.sleep_mode_brightness') | float }}"

- alias: laundry_room_washing_machine_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.laundry_room_washing_machine_water_sensor_water_leak_detected
      area: Laundry Room Washing Machine

- alias: laundry_room_water_heater_check_water_leak
  use_blueprint:
    path: check_water_leak.yaml
    input:
      binary_sensor: binary_sensor.laundry_room_water_heater_water_sensor_water_leak_detected
      area: Laundry Room Water Heater

- alias: laundry_room_deck_door_left_open
  trigger:
    entity_id: binary_sensor.deck_door_open
    platform: state
    to: 'on'
    for:
      minutes: 15
  action:
    service: notify.notify
    data_template:
      message: Deck door is still open!
      data:
        push:
          badge: 1

- alias: laundry_room_deck_door_relock
  trigger:
    entity_id: binary_sensor.deck_door_open
    platform: state
    to: 'off'
    for:
      minutes: 60
  action:
    service: lock.lock
    data:
      entity_id: lock.deck_door_lock

- alias: laundry_room_deck_door_notify_unlocked
  trigger:
    entity_id: lock.deck_door_lock
    platform: state
    to: 'unlocked'
    for:
      minutes: 120
  action:
    service: notify.notify
    data:
      message: Deck door is still unlocked!
      data:
        push:
          badge: 1
