- alias: laundry_room_timer_lights_finished
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.laundry_room_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.laundry_room

- alias: laundry_room_lights_on
  trigger:
    platform: state
    entity_id: light.laundry_room
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.laundry_room_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"

- alias: laundry_room_motion_detected
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_room_motion
    to: 'on'
  action:
    - service: timer.start
      data:
        entity_id: timer.laundry_room_lights
        duration: "{{ states('sensor.dynamic_light_timer_duration') }}"
    - condition: state
      entity_id: light.laundry_room
      state: 'off'
    - service: light.turn_on
      data:
        entity_id: light.laundry_room
        brightness_pct: "{{ states('sensor.default_indoor_brightness') | float }}"
