- alias: living_room_lights_sleep_mode_off
  use_blueprint:
    path: lights_on_sleep_mode_off.yaml
    input:
      light_entity: light.living_room

- alias: living_room_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.living_room

- alias: living_room_lights_home_on
  use_blueprint:
    path: lights_on_home_on.yaml
    input:
      light_entity: light.living_room

- alias: living_room_lights_home_off
  use_blueprint:
    path: lights_off_home_off.yaml
    input:
      light_entity: light.living_room

- alias: living_room_lights_time_of_day_change
  use_blueprint:
    path: lights_dim_time_of_day_brightness_change.yaml
    input:
      light_entity: light.living_room

- alias: living_room_accent_lights_nighttime_on
  use_blueprint:
    path: lights_on_nighttime_on.yaml
    input:
      light_entity: light.living_room_accent
      brightness_pct: 100

- alias: living_room_accent_lights_nighttime_off
  use_blueprint:
    path: lights_off_nighttime_off.yaml
    input:
      light_entity: light.living_room_accent

- alias: living_room_check_heat_fireplace
  trigger:
    - platform: time_pattern
      minutes: "/10"
  condition:
    condition: template
    value_template: "{{ state_attr('climate.living_room_heat', 'current_temperature') | float > 80 }}"
  action:
    - service: notify.notify
      continue_on_error: true
      data:
        message: Fireplace turning off due to excessive heat
        data:
          push:
            badge: 1
    - service: climate.turn_off
      continue_on_error: true
      data:
        entity_id: climate.living_room_heat

- alias: living_room_climate_motion_detected
  trigger:
    entity_id: binary_sensor.living_room_sensor_motion_detection
    platform: state
    to: 'on'
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.living_room_heat
      preset_mode: activity

- alias: living_room_climate_motion_idle
  trigger:
    entity_id: binary_sensor.living_room_sensor_motion_detection
    platform: state
    to: 'off'
    for:
      minutes: 30
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.living_room_heat
      preset_mode: comfort

- alias: living_room_climate_arrive_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: climate.turn_on
    data:
      entity_id: climate.living_room_heat

- alias: living_room_climate_depart_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: climate.turn_off
    data:
      entity_id: climate.living_room_heat

- alias: living_room_climate_sleep_mode_on
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: climate.turn_off
    data:
      entity_id: climate.living_room_heat

- alias: living_room_climate_sleep_mode_off
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: climate.turn_on
    data:
      entity_id: climate.living_room_heat

- alias: living_room_google_home_sleep_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'off'
    to: 'on'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.living_room_home

- alias: living_room_google_home_sleep_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'on'
    to: 'off'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_home
        volume_level: 0.50
