- alias: office_lights_sleep_mode_off
  use_blueprint:
    path: lights_on_sleep_mode_off.yaml
    input:
      light_entity: light.office

- alias: office_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.office

- alias: office_climate_motion_detected
  trigger:
    entity_id: binary_sensor.office_sensor_motion_detection
    platform: state
    to: 'on'
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.office_heat
      preset_mode: activity

- alias: office_climate_motion_idle
  trigger:
    entity_id: binary_sensor.office_sensor_motion_detection
    platform: state
    to: 'off'
    for:
      minutes: 15
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.office_heat
      preset_mode: comfort

- alias: office_climate_arrive_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: climate.turn_on
    data:
      entity_id: climate.office_heat

- alias: office_climate_depart_home
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: climate.turn_off
    data:
      entity_id: climate.office_heat

- alias: office_climate_sleep_mode_on
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'off'
    to: 'on'
  action:
    service: climate.turn_off
    data:
      entity_id: climate.office_heat

- alias: office_climate_sleep_mode_off
  trigger:
    entity_id: input_boolean.sleep_mode_enabled
    platform: state
    from: 'on'
    to: 'off'
  action:
    service: climate.turn_on
    data:
      entity_id: climate.office_heat

- alias: office_google_home_sleep_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'off'
    to: 'on'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.office_home

- alias: office_google_home_sleep_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'on'
    to: 'off'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.office_home
        volume_level: 0.50
