- alias: sunroom_door_left_open
  trigger:
    entity_id: binary_sensor.sunroom_door_open
    platform: state
    to: 'on'
    for:
      minutes: 15
  action:
    service: notify.notify
    data_template:
      message: Sunroom door is still open!
      data:
        push:
          badge: 1
