- alias: sunroom_lights_sleep_mode_on
  use_blueprint:
    path: lights_off_sleep_mode_on.yaml
    input:
      light_entity: light.sunroom

- alias: sunroom_lights_home_off
  use_blueprint:
    path: lights_off_home_off.yaml
    input:
      light_entity: light.sunroom

- alias: sunroom_door_left_open
  trigger:
    entity_id: binary_sensor.sunroom_door_open
    platform: state
    to: 'on'
    for:
      minutes: 15
  action:
    service: notify.notify
    data_template:
      message: Sunroom door is still open!
      data:
        push:
          badge: 1

- alias: sunroom_door_relock
  trigger:
    entity_id: binary_sensor.sunroom_door_open
    platform: state
    to: 'off'
    for:
      minutes: 60
  action:
    service: lock.lock
    data:
      entity_id: lock.sunroom_door_lock

- alias: sunroom_door_notify_unlocked
  trigger:
    entity_id: lock.sunroom_door_lock
    platform: state
    to: 'unlocked'
    for:
      minutes: 120
  action:
    service: notify.notify
    data:
      message: Sunroom door is still unlocked!
      data:
        push:
          badge: 1

- alias: sunroom_google_home_sleep_mode_on
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'off'
    to: 'on'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.sunroom_home

- alias: sunroom_google_home_sleep_mode_off
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'on'
    to: 'off'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.sunroom_home
        volume_level: 0.50
