- alias: sunroom_door_left_open
  trigger:
    entity_id: binary_sensor.sunroom_door_open
    platform: state
    to: 'on'
    for:
      minutes: 15
  action:
    service: notify.notify
    data_template:
      message: Sunroom door is still open!
      data:
        push:
          badge: 1

- alias: sunroom_door_left_unlocked
  trigger:
    entity_id: binary_sensor.sunroom_door_open
    platform: state
    to: 'off'
    for:
      minutes: 60
  action:
    service: lock.lock
    data:
      entity_id: lock.sunroom_door_lock
