- alias: vacuum_start_infinite_clean_mode
  trigger:
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id: input_boolean.roomba_infinite_clean_mode
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.roomba_infinite_clean_mode
      state: 'on'
    - condition: state
      entity_id: vacuum.roomba
      state: 'docked'
    - condition: numeric_state
      entity_id: sensor.roomba_battery_level
      above: 90
  action:
    service: vacuum.start
    data:
      entity_id: vacuum.roomba

- alias: vacuum_stop_infinite_clean_mode
  trigger:
    - platform: state
      entity_id: input_boolean.roomba_infinite_clean_mode
      to: 'off'
  action:
    - service: vacuum.stop
      data:
        entity_id: vacuum.roomba
    - service: vacuum.return_to_base
      data:
        entity_id: vacuum.roomba

- alias: vacuum_start_night_cleaning
  trigger:
    platform: state
    entity_id: sensor.sleep_mode
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.roomba_schedule_night_cleaning
    state: 'on'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.roomba_infinite_clean_mode

- alias: vacuum_end_night_cleaning
  trigger:
    platform: state
    entity_id: sensor.sleep_mode
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.roomba_schedule_night_cleaning
    state: 'on'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.roomba_infinite_clean_mode
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.roomba_schedule_night_cleaning
    - service: vacuum.stop
      data:
        entity_id: vacuum.roomba
    - service: vacuum.return_to_base
      data:
        entity_id: vacuum.roomba

- alias: vacuum_check_night_cleaning_supplemental_lighting
  trigger:
    platform: time_pattern
    minutes: '/5'
  condition:
    - condition: state
      entity_id: sensor.sleep_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.roomba_schedule_night_cleaning
      state: 'on'
    - condition: state
      entity_id: light.downstairs
      state: 'off'
  action:
    service: python_script.light_turn_on
    data:
      entity_id: light.downstairs
      brightness: 125
