- alias: state_door_closed_extended_time
  trigger:
    - entity_id: binary_sensor.front_door_open
      platform: state
      to: 'off'
      for:
        minutes: 15
    - entity_id: binary_sensor.sunroom_door_open
      platform: state
      to: 'off'
      for:
        minutes: 60
    - entity_id: binary_sensor.deck_door_open
      platform: state
      to: 'off'
      for:
        minutes: 60
    - entity_id: binary_sensor.garage_back_door_open
      platform: state
      to: 'off'
      for:
        minutes: 60
  action:
    service: lock.lock
    data_template:
      entity_id: >
        {% if trigger.entity_id == 'binary_sensor.deck_door_open' %}
          lock.deck_door_lock
        {% elif trigger.entity_id == 'binary_sensor.front_door_open' %}
          lock.front_door_lock
        {% elif trigger.entity_id == 'binary_sensor.garage_back_door_open' %}
          lock.garage_door_lock
        {% elif trigger.entity_id == 'binary_sensor.sunroom_door_open' %}
          lock.sunroom_door_lock
        {% endif %}

- alias: state_door_open_extended_time
  trigger:
    - entity_id: binary_sensor.front_door_open
      platform: state
      to: 'on'
      for:
        minutes: 15
    - entity_id: binary_sensor.sunroom_door_open
      platform: state
      to: 'on'
      for:
        minutes: 15
    - entity_id: binary_sensor.deck_door_open
      platform: state
      to: 'on'
      for:
        minutes: 15
    - entity_id: binary_sensor.garage_back_door_open
      platform: state
      to: 'on'
      for:
        minutes: 15
    - entity_id: cover.garage_door_opener
      platform: state
      to: 'open'
      for:
        minutes: 15
  action:
    service: notify.notify
    data_template:
      message: >
        {% if trigger.entity_id == 'binary_sensor.deck_door_open' %}
          Deck door is still open!
        {% elif trigger.entity_id == 'binary_sensor.front_door_open' %}
          Front door is still open!
        {% elif trigger.entity_id == 'binary_sensor.garage_back_door_open' %}
          Garage back door is still open!
        {% elif trigger.entity_id == 'binary_sensor.sunroom_door_open' %}
          Sunroom door is still open!
        {% elif trigger.entity_id == 'cover.garage_door_opener' %}
          Garage door is still open!
        {% else %}
          A door is still open!
        {% endif %}
      data:
        push:
          badge: 1
