- alias: state_fountain_poor_conditions_changed
  trigger:
    platform: state
    entity_id: binary_sensor.poor_fountain_conditions
  action:
    service_template: >
      {% if trigger.to_state.state == 'on' %}
        switch.turn_off
      {% else %}
        switch.turn_on
      {% endif %}
    data:
      entity_id: switch.fountain
