- alias: state_home_off
  trigger:
    entity_id: binary_sensor.home
    platform: state
    to: 'on'
    from: 'off'
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: light.turn_on
      data:
        entity_id: light.inside
        brightness_pct: "{{ states('input_number.light_brightness') | float }}"
        transition: "{{ states('input_number.light_transition') | float }}"
    - service: nest.set_away_mode
      data:
        away_mode: home

- alias: state_home_on
  trigger:
    entity_id: binary_sensor.home
    platform: state
    to: 'off'
    from: 'on'
  action:
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: light.turn_off
      data:
        entity_id: light.inside
        transition: "{{ states('input_number.light_transition') | float }}"
    - service: nest.set_away_mode
      data:
        away_mode: away
