- alias: state_home_on
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'off'
    to: 'on'
  action:
    - service: alarm_control_panel.alarm_disarm
      continue_on_error: true
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: light.turn_on
      continue_on_error: true
      data:
        entity_id: light.inside
    - service: climate.turn_on
      continue_on_error: true
      data:
        entity_id:
            - climate.living_room_heat
            - climate.family_room_heat
            - climate.office_heat

- alias: state_home_off
  trigger:
    entity_id: binary_sensor.home
    platform: state
    from: 'on'
    to: 'off'
  action:
    - service: alarm_control_panel.alarm_arm_away
      continue_on_error: true
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: light.turn_off
      continue_on_error: true
      data:
        entity_id: light.inside
    - service: climate.turn_off
      continue_on_error: true
      data:
        entity_id:
          - climate.living_room_heat
          - climate.family_room_heat
          - climate.office_heat

