- alias: state_lights_backyard_on
  trigger:
    platform: state
    entity_id: light.backyard
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.backyard_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"

- alias: state_lights_bathroom_downstairs_on
  trigger:
    platform: state
    entity_id: light.bathroom_downstairs
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.bathroom_downstairs_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"

- alias: state_lights_bathroom_upstairs_on
  trigger:
    platform: state
    entity_id: light.bathroom_upstairs
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.bathroom_upstairs_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"

- alias: state_lights_laundry_room_on
  trigger:
    platform: state
    entity_id: light.laundry_room
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.laundry_room_lights
      duration: "{{ states('sensor.dynamic_light_timer_duration') }}"
