- alias: state_lights_backyard_on
  trigger:
    platform: state
    entity_id: light.backyard
    to: 'on'
  action:
    service: script.backyard_timer_start

- alias: state_lights_bathroom_downstairs_on
  trigger:
    platform: state
    entity_id: light.bathroom_downstairs
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.bathroom_downstairs_lights
      duration: >
        {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
          00:01:00
        {% else %}
          00:15:00
        {% endif %}

- alias: state_lights_bathroom_upstairs_on
  trigger:
    platform: state
    entity_id: light.bathroom_upstairs
    to: 'on'
  action:
    service: script.upstairs_bathroom_timer_start

- alias: state_lights_laundry_room_on
  trigger:
    platform: state
    entity_id: light.laundry_room
    to: 'on'
  action:
    service: timer.start
    data:
      entity_id: timer.laundry_room_lights
      duration: >
        {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
          00:01:00
        {% else %}
          00:15:00
        {% endif %}
