- alias: state_lights_on_for_low_visibility
  trigger:
    platform: state
    entity_id: binary_sensor.low_visibility
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.outside
      brightness_pct: 100

- alias: state_lights_off_for_high_visibility
  trigger:
    platform: state
    entity_id: binary_sensor.low_visibility
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.outside
