- alias: state_motion_mailbox_detected
  trigger:
    entity_id: binary_sensor.mailbox_motion
    platform: state
    to: 'on'
  action:
    service: notify.notify
    data:
      message: You've got mail!
      data:
        push:
          badge: 1

- alias: state_motion_living_room_detected
  trigger:
    entity_id: binary_sensor.living_room_sensor_motion_detection
    platform: state
    to: 'on'
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.living_room_heat
      preset_mode: activity

- alias: state_motion_living_room_idle
  trigger:
    entity_id: binary_sensor.living_room_sensor_motion_detection
    platform: state
    to: 'off'
    for:
      minutes: 30
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.living_room_heat
      preset_mode: comfort

- alias: state_motion_family_room_detected
  trigger:
    entity_id: binary_sensor.family_room_motion
    platform: state
    to: 'on'
  action:
    service: climate.set_preset_mode
    data:
      entity_id:
        - climate.family_room_heat
        - climate.family_room_ac
      preset_mode: activity

- alias: state_motion_family_room_idle
  trigger:
    entity_id: binary_sensor.family_room_motion
    platform: state
    to: 'off'
    for:
      minutes: 15
  action:
    service: climate.set_preset_mode
    data:
      entity_id:
        - climate.family_room_heat
        - climate.family_room_ac
      preset_mode: comfort

- alias: state_motion_office_detected
  trigger:
    entity_id: binary_sensor.office_sensor_motion_detection
    platform: state
    to: 'on'
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.office_heat
      preset_mode: activity

- alias: state_motion_office_idle
  trigger:
    entity_id: binary_sensor.office_sensor_motion_detection
    platform: state
    to: 'off'
    for:
      minutes: 15
  action:
    service: climate.set_preset_mode
    data:
      entity_id: climate.office_heat
      preset_mode: comfort
