- alias: state_motion_mailbox_detected
  trigger:
    entity_id: binary_sensor.mailbox_motion
    platform: state
    to: 'on'
  action:
    service: notify.notify
    data:
      message: You've got mail!
      data:
        push:
          badge: 1

- alias: state_motion_downstairs_bathroom_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_bathroom_motion
      to: 'on'
  action:
    - choose:
        - conditions:
            condition: state
            entity_id: input_boolean.sleep_mode_enabled
            state: 'on'
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.bathroom_downstairs
                brightness_pct: 1
      default:
        - service: light.turn_on
          data:
            entity_id: light.bathroom_downstairs
    - choose:
        - conditions:
            condition: state
            entity_id: input_boolean.sleep_mode_enabled
            state: 'on'
          sequence:
            - service: timer.start
              data:
                entity_id: timer.downstairs_bathroom_lights
                duration:
                  seconds: 60
      default:
        - service: timer.start
          data:
            entity_id: timer.downstairs_bathroom_lights
            duration:
              minutes: 15

- alias: state_motion_upstairs_bathroom_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_bathroom_motion
      to: 'on'
  action:
    - choose:
        - conditions:
            condition: state
            entity_id: input_boolean.sleep_mode_enabled
            state: 'on'
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.bathroom_upstairs
                brightness_pct: 1
      default:
        - service: light.turn_on
          data:
            entity_id: light.bathroom_upstairs
    - choose:
        - conditions:
            condition: state
            entity_id: input_boolean.sleep_mode_enabled
            state: 'on'
          sequence:
            - service: timer.start
              data:
                entity_id: timer.upstairs_bathroom_lights
                duration:
                  seconds: 60
      default:
        - service: timer.start
          data:
            entity_id: timer.upstairs_bathroom_lights
            duration:
              minutes: 15
