- alias: state_motion_mailbox_detected
  trigger:
    entity_id: binary_sensor.mailbox_motion
    platform: state
    to: 'on'
  action:
    service: script.post_slack_message
    data:
      message: You've got mail!

- alias: state_motion_front_yard_detected
  trigger:
    platform: state
    entity_id:
      - binary_sensor.porch_camera_motion_detected
      - binary_sensor.garage_camera_motion_detected
    to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.late_nighttime
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.front_yard
        brightness_pct: 100
        transition: "{{ states('input_number.light_transition') | float }}"
    - service: timer.start
      data:
        entity_id: timer.brighten_front_yard
        duration: '00:05:00'

- alias: state_motion_backyard_detected
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backyard_camera_person_detected
        - binary_sensor.deck_camera_person_detected
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.low_visibility
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.backyard
        brightness_pct: 100
        transition: "{{ states('input_number.light_transition') | float }}"
    - service: script.backyard_timer_start

- alias: state_motion_downstairs_bathroom_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_bathroom_motion
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom_downstairs
        brightness_pct: >
          {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
            1
          {% else %}
            {{ states('input_number.light_brightness') | float }}
          {% endif %}
        transition: "{{ states('input_number.light_transition') | float }}"
    - service: timer.start
      data:
        entity_id: timer.downstairs_bathroom_lights
        duration: >
          {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
            00:01:00
          {% else %}
            00:15:00
          {% endif %}

- alias: state_motion_upstairs_bathroom_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_bathroom_motion
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom_upstairs
        brightness_pct: >
          {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
            1
          {% else %}
            {{ states('input_number.light_brightness') | float }}
          {% endif %}
        transition: "{{ states('input_number.light_transition') | float }}"
    - service: timer.start
      data:
        entity_id: timer.upstairs_bathroom_lights
        duration: >
          {% if is_state('input_boolean.sleep_mode_enabled', 'on') %}
            00:01:00
          {% else %}
            00:15:00
          {% endif %}
