- alias: state_sleep_mode_changed_on_to_off
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'on'
    to: 'off'
  mode: restart
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.master_bedroom_home
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: script.reset_google_home_volumes
    - service: light.turn_on
      data:
        entity_id: light.inside
        brightness_pct: 25
        transition: 30
    - delay: 30
    - service: light.turn_on
      data:
        entity_id: light.inside
        brightness_pct: 100
        transition: 3600

- alias: state_sleep_mode_changed_off_to_on
  trigger:
    platform: state
    entity_id: input_boolean.sleep_mode_enabled
    from: 'off'
    to: 'on'
  mode: restart
  action:
    - service: script.media_devices_off
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.abode_alarm
    - service: script.play_sleep_sounds
    - service: light.turn_on
      data:
        entity_id: light.inside
        brightness_pct: 1
    - service: light.turn_off
      data:
        entity_id: light.inside
