- alias: event_button_master_bedroom_right_pressed
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 31
      value: KeyPressed
  action:
    service: input_boolean.toggle
    data:
      entity_id: input_boolean.sleep_mode_enabled

- alias: event_button_master_bedroom_right_double_pressed
  trigger:
    platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 31
      value: KeyPressed2x
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_upstairs
      transition: "{{ states('input_number.light_transition') | float }}"

- alias: event_button_living_room_remote_1_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "001"
  action:
    service: light.turn_on
    data:
      entity_id: light.inside_core
      brightness_pct: "{{ states('input_number.light_brightness') | float }}"
      transition: "{{ states('input_number.light_transition') | float }}"

- alias: event_button_living_room_remote_2_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "002"
  action:
    service: light.turn_on
    data:
      entity_id: light.inside_core
      brightness_pct: "{{ states('input_number.light_brightness') | float / 2 }}"
      transition: "{{ states('input_number.light_transition') | float }}"

- alias: event_button_living_room_remote_3_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "003"
  action:
    service: light.turn_off
    data:
      entity_id: light.inside_core
      transition: "{{ states('input_number.light_transition') | float }}"

- alias: event_button_living_room_remote_middle_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "004"
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      flash: short
