- alias: event_button_living_room_remote_1_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "001"
  action:
    service: light.turn_on
    data:
      entity_id: light.inside
      brightness_pct: 100

- alias: event_button_living_room_remote_2_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "002"
  action:
    service: light.turn_on
    data:
      entity_id: light.inside
      brightness_pct: 50

- alias: event_button_living_room_remote_3_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "003"
  action:
    service: light.turn_off
    data:
      entity_id: light.inside

- alias: event_button_living_room_remote_middle_pressed
  trigger:
    - platform: event
      event_type: zwave_js_value_notification
      event_data:
        node_id: 5
        property_key: "004"
  action:
    service: light.toggle
    data:
      entity_id: light.living_room
