- alias: event_timer_bathroom_downstairs_idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bathroom_downstairs_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_downstairs

- alias: event_timer_bathroom_upstairs_idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bathroom_upstairs_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_upstairs

- alias: event_timer_laundry_room_idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.laundry_room_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.laundry_room

- alias: event_timer_backyard_idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.backyard_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.backyard

- alias: event_timer_front_yard_idle_late_nighttime
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.brighten_front_yard
  condition:
    condition: state
    entity_id: binary_sensor.late_nighttime
    state: 'on'
  action:
    service: script.fade_to_dim_front_yard
