- alias: event_timer_downstairs_bathroom_idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.downstairs_bathroom_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_downstairs
      transition: "{{ states('input_number.light_transition') | float }}"

- alias: event_timer_upstairs_bathroom_idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.upstairs_bathroom_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom_upstairs
      transition: "{{ states('input_number.light_transition') | float }}"

- alias: event_timer_backyard_idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.backyard_lights
  action:
    service: light.turn_off
    data:
      entity_id: light.backyard
      transition: "{{ states('input_number.light_transition') | float }}"

- alias: event_timer_front_yard_idle_late_nighttime
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.brighten_front_yard
  condition:
    condition: state
    entity_id: binary_sensor.late_nighttime
    state: 'on'
  action:
    service: script.fade_to_dim_front_yard
