- alias: front_yard_irrigation_maintenance_time
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  condition:
    - condition: time
      weekday:
        - sun
        - wed
    - condition: state
      entity_id: input_select.irrigation
      state: Maintenance
  action:
    - service: python_script.irrigation_run_maintenance
      data:
        zones:
          - 1
          - 2
          - 6
- alias: front_yard_irrigation_maintenance_supplemental_time
  trigger:
    platform: sun
    event: sunrise
    offset: '-01:00:00'
  condition:
    - condition: time
      weekday:
        - fri
    - condition: state
      entity_id: input_select.irrigation
      state: Maintenance
    - condition: state
      entity_id: binary_sensor.excessive_heat_today
      state: 'on'
  action:
    - service: python_script.irrigation_run_maintenance
      data:
        zones:
          - 1
          - 2
          - 6
