- alias: sun_lights_at_sunset
  trigger:
    platform: sun
    event: sunset
    offset: '00:15:00'
  action:
    service: script.outside_core_lights_on

- alias: sun_lights_at_sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: '-00:15:00'
  action:
    service: script.outside_lights_off
